pid_error:
  MIN_DISTANCE: 0.1
  MAX_DISTANCE: 30.0
  DESIRED_DISTANCE: .75

  CONTROL_DELAY_ESTIMATE: 0
  minLookDistance: 1
  lookDistanceMultiplier: 1

  currentMode: "left"
  currentEnumMode: 1
  currentGapAngle: 0

control:
  KP: 0.03
  KI: 0.000
  KD: 0.03

  KP_TM: 1
  KI_TM: 1
  KD_TM: 1

  MAX_VEL: 2
  MIN_VEL: 1
  MAX_STEERING_ANGLE: 20
  N: 1
  K: 0.5

instruction:
  goodGapThresh: .5
  consecutiveTurnIndicatorThresh: 5
  newInstructionGapCount: 1
  defaultInstruction: C
  instructionDirectory: '../explicit_instructions/'
  instructionFile: 'test_instructions.dat'
